I18NPROD-507-format-value-string-for-gift-card
Squarespace/template-engine pull request #9
Opened 2021-07-27 13:21 UTC by kllewellyn

## What does this PR do?

Adds a method to `formatters.commerce.ts` that translates the "Value" string displayed when a product is a gift card and defaults to the user input variant name otherwise.

## Why is this important?

Currently there is a bug where the text above the gift card option drop-down displayed "Value" in English in all languages. This formatting method solves this bug.

## What high level changes did you make to the code to accomplish that goal?

* Added a method to `formatters.commerce.ts` that resolves the `displayText` based on the locale if a product is a gift card type otherwise it returns the `name` of the variant
* Changed the `variant-option-title` tag within `variants-select.html` and `variants-select.json` to `{displayName}` with a default to `name` for non-gift card product types.

## Anything else?

This change also required adding the string `Value` to the `products-en-US.json` and `products-2.0-en-US.json` files within site-server to be translated into all languages. That PR can be found [here](https://github.com/sqsp/squarespace-v6/pull/11407) and will need to be merged and have translations returned before these changes are incorporated. This change keeps template-engine parallel with template-compiler. The equivalent changes made in template-compiler can be found in [this PR](https://github.com/Squarespace/template-compiler/pull/26).

## How was this tested?

- [x] Wrote additional tests for this functionality

2021-07-28 13:56 UTC, phensley commented
@kllewellyn  The `f-variants-select-#.html` files don't appear to be identical with your changes to the Java compiler. 
For example I'm seeing a diff for test case `4`:

```
4c4
<     "productVariantSelectText": "Get foobar"
---
>     "giftCardVariantSelectText": "Get foobar"
9c9
<       "productType": 1,
---
>       "productType": 4,
25c25
<     <div class="variant-option-title">fit: </div>
---
>     <div class="variant-option-title">Value: </div>
40c40
<     <div class="variant-option-title">color: </div>
---
>     <div class="variant-option-title">Value: </div>
```

2021-07-28 14:01 UTC, kllewellyn commented
Ah I see - yes for Java compiler I changed this to productType 1 let me make those changes right now.

2021-07-28 14:01 UTC, phensley requested changes
Ensure numbered test cases are identical with Java compiler.

2021-07-28 18:58 UTC, kllewellyn commented
> Ensure numbered test cases are identical with Java compiler.

This has been updated

2021-07-28 19:06 UTC, phensley approved these changes

2021-07-29 14:31 UTC, merged

2021-07-29 14:35 UTC, phensley commented
@kllewellyn This is released in `2.8.17`